"""Complete model graph for schema creation and Alembic metadata."""

import app.models.activity_log  # noqa: F401
import app.models.agent  # noqa: F401
import app.models.agent_credential  # noqa: F401
import app.models.audit  # noqa: F401
import app.models.channel_config  # noqa: F401
import app.models.channel_type_default  # noqa: F401
import app.models.chat_compaction  # noqa: F401
import app.models.chat_session  # noqa: F401
import app.models.cli_tool_binary  # noqa: F401
import app.models.dingtalk_provisioning  # noqa: F401
import app.models.focus  # noqa: F401
import app.models.gateway_message  # noqa: F401
import app.models.identity  # noqa: F401
import app.models.invitation_code  # noqa: F401
import app.models.llm  # noqa: F401
import app.models.mcp_server  # noqa: F401
import app.models.notification  # noqa: F401
import app.models.okr  # noqa: F401
import app.models.onboarding  # noqa: F401
import app.models.org  # noqa: F401
import app.models.participant  # noqa: F401
import app.models.personal_access_token  # noqa: F401
import app.models.plaza  # noqa: F401
import app.models.project  # noqa: F401
import app.models.published_page  # noqa: F401
import app.models.scene  # noqa: F401
import app.models.schedule  # noqa: F401
import app.models.skill  # noqa: F401
import app.models.speech_recognition_config  # noqa: F401
import app.models.subagent_run  # noqa: F401
import app.models.system_settings  # noqa: F401
import app.models.task  # noqa: F401
import app.models.tenant  # noqa: F401
import app.models.tenant_setting  # noqa: F401
import app.models.tool  # noqa: F401
import app.models.trigger  # noqa: F401
import app.models.trigger_execution  # noqa: F401
import app.models.user  # noqa: F401
import app.models.workspace  # noqa: F401
