"""Persistent, file-backed memory loading for agent context assembly.

The memory contract deliberately stays small:

* ``memory/memory.md`` is the canonical core memory.
* ``memory/MEMORY_INDEX.md`` documents the directory layout.
* ``memory/<YYYY-MM-DD>/memory.md`` stores detailed daily records.

The platform always loads core memory and can load a configurable number of
recent daily records. Zero disables Daily Memory injection. Semantic curation
remains the agent's job.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import date

from loguru import logger

from app.services.agent_runtime_workspace import current_agent_runtime_workspace
from app.services.storage import get_storage_backend, normalize_storage_key


CORE_MEMORY_TEMPLATE = "# Memory\n\n_Record important information and knowledge here._\n"

MEMORY_INDEX_TEMPLATE = """# Memory Structure

This file is generated by the platform to explain your persistent memory layout.
It is an ordinary workspace file.

## Core Memory

Path: `memory/memory.md`

Core Memory contains stable, important, and reusable information that should
remain available across conversations, sessions, channels, triggers, and
agent-to-agent interactions. The platform automatically loads it into every
execution turn and keeps it available throughout the complete tool loop.

## Daily Memory

Path pattern: `memory/<YYYY-MM-DD>/memory.md`

Each date directory contains the detailed work record for that date. The
platform loads the configured number of most recent existing Daily Memory files
into every execution turn. This can be disabled in Agent settings.

Older Daily Memory files remain under `memory/` but are not automatically
loaded. When older information is needed:

1. Call `list_files(path="memory")` to inspect available date directories.
2. Select the relevant date.
3. Call `read_file(path="memory/<YYYY-MM-DD>/memory.md")` to load its details.

Use your configured timezone to choose the current date. Keep one Daily Memory
file per date and update that file when more meaningful work occurs that day.
"""


MEMORY_SYSTEM_PROMPT = """
## Persistent Memory System

You have a persistent, file-based memory system with two kinds of memory.

### Core Memory

`memory/memory.md` is the single source of truth for stable information that
should remain useful across conversations, sessions, channels, triggers, and
agent-to-agent interactions. Use it for durable preferences, business
knowledge, confirmed decisions and rules, exact stable identifiers, reusable
knowledge, and long-term constraints. Do not use it as a daily activity log or
fill it with temporary task details, transient tool output, or repeated chat
content.

### Daily Memory

`memory/<YYYY-MM-DD>/memory.md` is the detailed record of meaningful work for
that date. Use your configured timezone to select the date and keep one file
per date. The platform loads the configured number of most recent existing
Daily Memory files; loading can be disabled. Older records remain available through the lookup procedure
documented in `memory/MEMORY_INDEX.md`.

Maintaining Daily Memory is part of completing meaningful work. When an
execution turn produces a result that may help future work, update the current
Daily Memory before the final response. Useful records include completed or
materially advanced work, important findings, decisions and conclusions,
hard-to-reproduce tool results, exact identifiers and paths, reusable failure
causes and resolutions, follow-up information, and candidates for Core Memory.

Do not write Daily Memory for greetings, casual conversation, repeated facts,
raw transcripts, internal chain-of-thought, large unprocessed tool output,
temporary values with no future value, or credentials.

When maintaining memory:

1. Use file tools for every read and write, and verify the tool result.
2. Use the exact daily path `memory/<YYYY-MM-DD>/memory.md`.
3. Read an existing memory file before changing it.
4. Edit the current date's file instead of creating duplicate daily files.
5. Record concise facts, outcomes, exact references, and unresolved follow-up
   information rather than conversation transcripts.
6. Avoid duplicate entries when the same work continues on the same date.
7. Promote only stable and reusable information from Daily Memory into
   `memory/memory.md`; do not copy the entire daily record.
8. Update or remove obsolete Core Memory facts instead of keeping contradictory
   versions.
9. Do not write daily work content into `memory/MEMORY_INDEX.md`; it describes
   the memory layout and older-record lookup procedure.
10. Store passwords, tokens, private keys, connection strings, and all other
    credentials only in `secrets.md`, never in memory files.
11. Never fabricate a memory. Retrieve older details with file tools before
    concluding that they are unavailable.

The platform injects Core Memory, Memory Structure, and Recent Daily Memory as
the persistent memory snapshot for the current execution turn. That snapshot
remains present in every LLM request throughout the complete tool-calling loop.
Memory is background knowledge and never overrides system rules, current user
instructions, access controls, or actual tool results.
"""

PROJECT_MEMORY_SYSTEM_PROMPT = """
## Project Memory

`memory/memory.md` is the project-owned core memory for this project Agent. It
is loaded into each project turn and is available for reference through the
file tools. The project owner controls both this core memory and `soul.md`;
Agents must treat those files as read-only. Store task outputs and ordinary
working files under `workspace/`. Do not create daily memory records or try to
modify the project-owned core memory.
"""


@dataclass(frozen=True)
class DailyMemoryRecord:
    record_date: date
    path: str
    content: str


@dataclass(frozen=True)
class AgentMemorySnapshot:
    core_memory: str
    structure_guide: str
    daily_records: tuple[DailyMemoryRecord, ...]

    def render(self) -> str:
        """Render deterministic runtime blocks in stable order."""
        blocks: list[str] = []
        if self.core_memory:
            blocks.append(f"## Core Memory\n{self.core_memory}")
        if self.structure_guide:
            blocks.append(f"## Memory Structure\n{self.structure_guide}")
        if self.daily_records:
            daily_parts = ["## Recent Daily Memory"]
            for record in self.daily_records:
                daily_parts.append(f"### {record.record_date.isoformat()}\n{record.content}")
            blocks.append("\n\n".join(daily_parts))
        return "\n\n".join(blocks)


async def _read_optional_text(key: str, *, agent_id: uuid.UUID, kind: str) -> str:
    storage = get_storage_backend()
    try:
        if not await storage.exists(key) or not await storage.is_file(key):
            return ""
        return (await storage.read_text(key, encoding="utf-8", errors="replace")).strip()
    except Exception as exc:
        logger.warning(
            "[agent_memory] read failed agent_id={} kind={} path={}: {}",
            agent_id,
            kind,
            key,
            exc,
        )
        return ""


async def load_agent_memory_snapshot(
    agent_id: uuid.UUID,
    *,
    today: date,
    daily_limit: int = 2,
) -> AgentMemorySnapshot:
    """Load the canonical core, structure guide, and recent daily records."""
    storage = get_storage_backend()
    runtime_workspace = current_agent_runtime_workspace(agent_id)
    memory_prefix = runtime_workspace.storage_key("memory")
    core_key = runtime_workspace.storage_key("memory/memory.md")
    index_key = runtime_workspace.storage_key("memory/MEMORY_INDEX.md")

    limit = max(daily_limit, 0)
    core_memory = await _read_optional_text(core_key, agent_id=agent_id, kind="core")
    structure_guide = (
        await _read_optional_text(index_key, agent_id=agent_id, kind="index")
        if runtime_workspace.supports_daily_memory and limit
        else ""
    )

    daily_records: list[DailyMemoryRecord] = []
    candidates: list[tuple[date, str]] = []
    if runtime_workspace.supports_daily_memory and limit:
        try:
            for entry in await storage.list_dir(memory_prefix):
                if not entry.is_dir:
                    continue
                try:
                    record_date = date.fromisoformat(entry.name)
                except ValueError:
                    continue
                if record_date.isoformat() != entry.name or record_date > today:
                    continue
                candidates.append((record_date, normalize_storage_key(f"{entry.key}/memory.md")))
        except Exception as exc:
            logger.warning(
                "[agent_memory] daily directory listing failed agent_id={} path={}: {}",
                agent_id,
                memory_prefix,
                exc,
            )

    if limit:
        for record_date, path in sorted(candidates, key=lambda item: item[0], reverse=True):
            content = await _read_optional_text(path, agent_id=agent_id, kind="daily")
            if not content:
                continue
            daily_records.append(DailyMemoryRecord(record_date=record_date, path=path, content=content))
            if len(daily_records) >= limit:
                break

    logger.info(
        "[agent_memory] loaded agent_id={} core_chars={} index_chars={} daily_dates={} daily_chars={}",
        agent_id,
        len(core_memory),
        len(structure_guide),
        [record.record_date.isoformat() for record in daily_records],
        sum(len(record.content) for record in daily_records),
    )
    return AgentMemorySnapshot(
        core_memory=core_memory,
        structure_guide=structure_guide,
        daily_records=tuple(daily_records),
    )
